[cook]
; AutoCook 设置
endpoint=http://47.94.95.163:8887/
; 进入时要发送的消息
entermsg={TIME}好呀，可以打3个精英怪刷点摩拉不~~
; 进入时要发送的表情编号，0表示不发送表情
enteremo=2
; 成功退出时要发送的消息
successmsg=好的，我去换个号等会跟朋友过来~~ 谢谢~~
; 成功退出时要发送的表情编号，0表示不发送表情
successemo=0
; 被拒绝退出时要发送的消息
exitmsg=打扰了！
; 被拒绝退出时要发送的表情编号，0表示不发送表情
exitemo=0
; 无响应自动退出时间，单位为秒，0表示不超时
timeout=40
; 自动退出时要发送的消息
timeoutmsg=_(:з」∠)_
; 自动退出时要发送的表情编号，0表示不发送表情
timeoutemo=0
; 是否检查地图 1表示检查 0表示不检查
checkmap=1

