[cook]
; AutoCook 设置
; 服务器地址 格式: https://服务器网址/r/<房间号>/
endpoint=http://47.94.95.163:8887/r/default/
; 厨师名
cooker=香菱
; 进入时要发送的消息
entermsg={TIME}好呀，可以让我朋友进来打3个怪不~~
; 进入时要发送的表情编号，0表示不发送表情
enteremo=2
; 成功的正则表达式
successpattern=^[好哦嗯可行来进走去肘中]|没事|无所谓|都[行好可]|[好行][的把吧啊]|自[便取]|[打请]去?[便打把吧呗]|打$|随[遍便意]|^1|冲冲冲|申请|well|go|en|^o$|欧克|阔以|^可以|彳[亍于]|ok|^hao|^keyi|^ky|^qu|^zou|一起|没有?问题|当然|欢迎|天经地义
; 成功时要发送的消息
successmsg=好的，我先走了，我朋友等会过来~~ 谢谢老板~~
; 成功时要发送的表情编号，0表示不发送表情
successemo=0
; 拒绝的正则表达式
exitpattern=^拒绝|别打|不[好可行能]|^不打?$|no|shg|珊瑚宫|留着|[4四]连|-6|刚打过了|看下?签名
; 被拒绝退出时要发送的消息
exitmsg=打扰了！
; 被拒绝退出时要发送的表情编号，0表示不发送表情
exitemo=0
; 无响应自动退出时间，单位为秒，0表示不超时
timeout_noreply_wait=30
; 自动退出时要发送的消息
timeout_noreply_msg=_(:з」∠)_
; 自动退出时要发送的表情编号，0表示不发送表情
timeout_noreply_emo=0
; 无回复时检测签名的正则 留空表示不检测 以这种方式添加的UID会在cooker之前加上[挂]
timeout_noreply_sign_pattern=挂机|自取|随意
; 地主回复时自动退出时间，单位为秒，0表示不超时
timeout_reply_wait=50
; 地主回复但超时要发送的消息
timeout_reply_msg=_(:з」∠)_我先走了，行的话一会让他们进吧！
; 地主回复但超时要发送的表情编号，0表示不发送表情
timeout_reply_emo=0
; 地主回复但超时要添加的UID格式，留空表示不添加 可用变量: {UID} {MSG}
timeout_reply_add_fmt={UID}说: {MSG} (未识别的消息)

; 是否检查地图 1表示检查 0表示不检查
checkmap=1
; 地图检查F1的延迟时间，单位为秒
checkmap_f1_delay=2
; 地图检查每次点击的延迟时间，单位为秒
checkmap_step_delay=0.1
; 地图检查滚动条点击的延迟时间，单位为秒
checkmap_scroll_delay=0.3
; 地图检查的颜色检测延迟时间，单位为秒
checkmap_check_delay=0.5
